### ISSUE TITLE
I would like to have the mathlete's name shown at the bottom of the screen at all times

### ISSUE THREAD

**Issue by KenSStanley** [jakobcornell/dubois-traffic-puzzle#1]
I would like to have the mathlete's name shown at the bottom of the screen at all times. This allows the coach to check to see that the mathlete who is playing the game is the mathlete who is signed in.

**Comment by jakobcornell** [comment]
I've added a name label to the initial coach check and game play activities. I've committed to branch `mathlete-name` so that you can review the changes. If everything looks good, you can merge them into `master`.
