### ISSUE TITLE
Reduce the volume 

### ISSUE THREAD

**Issue by KenSStanley** [jakobcornell/dubois-traffic-puzzle#4]
The sound is nice but it is a bit too loud.

**Comment by jakobcornell** [comment]
Ah yes, I should have mentioned this at our final demo. I kept the media volume on the phone muted permanently for my testing, so I forgot about it. The Kyocera phones seem to have ridiculously loud speakers, which is probably the ultimate cause of this&mdash;I found the lowest volume setting to be plenty loud.
